### PR TITLE
Zaporizhzhia name update

### PR DESCRIPTION
**Pull request by Ilyahas**
https://en.wikipedia.org/wiki/Zaporizhzhia 
City in Ukraine. I saw you did changes for Kyiv, here is the same situation.

### CODE REVIEW

**Comment by omsrivastava** [comment]
Hi @Ilyahas, thanks for the update.
Just want to confirm. Is there any other city of Ukraine whose name needs to be updated? Then we can update it in the same version publishing.

**Comment by Ilyahas** [comment]
Just found: "Odessa" have to be "Odesa"

https://en.wikipedia.org/wiki/Odesa

https://github.com/omsrivastava/timezones-list/blob/master/src/timezones.json#L1601

**Comment by Ilyahas** [comment]
@omsrivastava can you update version and let's merge it :)

**Review by raphaelpinel — APPROVED** [review]

**Review by raphaelpinel — APPROVED** [review]

**Review by VitaliiLazebnyi — APPROVED** [review]
The PR still needs updating of versions just like it was done here: https://github.com/omsrivastava/timezones-list/pull/10/files
And it belive it's about time to merge it.

**Review by omsrivastava — APPROVED** [review]

**Comment by sandeepvasani** [comment]
These changes doesn't match with moment.js [timezone list](https://gist.github.com/diogocapela/12c6617fc87607d11fd62d2a4f42b02a) and breaks our integration. 
E.g
`Europe/Zaporozhye` to `Europe/Zaporizhzhia`

**Pull request merged**
